pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

include ':app'
include ':unityLibrary'
project(':unityLibrary').projectDir = file('../unity/Builds/AndroidLibrary/unityLibrary')

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        google()
        mavenCentral()
    }
}
