using BoardAI.Api.Infrastructure;
using BoardAI.Api.Services;

namespace BoardAI.Api.Tests;

/// <summary>
/// REV-03a regression: the C# API extraction of the nine real rule sets must
/// produce exactly the same IndexContract version line as the Python CLI.
/// Expected hashes are generated by animation/test_index_extraction.py over the
/// same repository data (source, path, concept_id, type, names, search_text).
/// </summary>
public sealed class IndexRealContentContractTests
{
    [Theory]
    [InlineData("agricola", "3796433e0d63a235")]
    [InlineData("ark-nova", "a25f3dc1e20c5590")]
    [InlineData("brass-birmingham", "6aec6eaf6ac0cbaa")]
    [InlineData("castles-of-burgundy", "f763f42b734c7a26")]
    [InlineData("civolution", "75a5bd36f360c382")]
    [InlineData("puerto-rico", "21f842ace2b37e6b")]
    [InlineData("seasons", "2df6ff09b492b711")]
    [InlineData("splendor", "03283886a77eb0de")]
    [InlineData("wingspan", "527374f5bc466f7d")]
    public void RealContent_IndexItemsMatchPythonContractVersion(string game, string expectedVersion)
    {
        using var content = new RulesContentStore(BoardPaths.GetBasePath());
        var service = new RulesIndexService(new RulesConceptCatalog(content), content, null);

        var items = service.GetIndexItems(game);
        var actual = IndexContract.ComputeIndexVersion(
            game, "bge-base-zh-v1.5-fp32", 768, items);

        Assert.Equal(expectedVersion, actual);
    }
}
